import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightToLine,
  ArrowUp,
  AtSign,
  Ban,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  Bot,
  Braces,
  Brain,
  Calendar,
  CalendarDays,
  Camera,
  Captions,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  CircleCheck,
  CircleDashed,
  CircleHelp,
  CircleSlash,
  Clapperboard,
  Clipboard,
  ClipboardList,
  ClipboardPaste,
  Clock,
  Clock3,
  Command,
  Compass,
  Copy,
  Cpu,
  Crop,
  Download,
  Edit3,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Film,
  Flag,
  Flame,
  Folder,
  Frame,
  Gauge,
  GitCompareArrows,
  Globe,
  GripVertical,
  Hand,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  History,
  Home,
  Image,
  ImageOff,
  ImagePlus,
  Inbox,
  Info,
  Keyboard,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  Link,
  Link2,
  List,
  ListChecks,
  ListFilter,
  Loader,
  Loader2,
  Lock,
  Maximize,
  Maximize2,
  Merge,
  MessageCircle,
  Mic,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MousePointer2,
  Move,
  MoveHorizontal,
  Package,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelRight,
  PanelRightClose,
  PanelRightOpen,
  Pause,
  Pen,
  Pin,
  Play,
  Plus,
  Puzzle,
  Quote,
  Radio,
  Redo2,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Rows2,
  Save,
  Scale,
  ScanFace,
  ScanLine,
  Scissors,
  Search,
  Settings,
  Settings2,
  ShieldCheck,
  SkipBack,
  SlidersHorizontal,
  Sparkle,
  Sparkles,
  SplitSquareHorizontal,
  Star,
  Sun,
  Tag,
  Tags,
  Target,
  TextCursorInput,
  Trash,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Type,
  Undo2,
  Unlock,
  Upload,
  UploadCloud,
  UserPlus,
  Users,
  Volume2,
  VolumeX,
  WandSparkles,
  Wrench,
  X,
  XCircle,
  Youtube,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react';

// ─────────────────────────────────────────────────────────────────
// D-599 · Ponte entre o handoff e o lucide-react.
//
// O protótipo escreve `<l-icon name="chevron-right">` — kebab-case,
// o mesmo vocabulário do icons.js que ele carrega. Manter esse nome
// vivo no código deixa a tradução do design 1:1: dá para conferir
// tela e arquivo lado a lado sem traduzir nome de ícone na cabeça.
//
// O mapa é explícito de propósito: um `import * as Lucide` resolveria
// em uma linha, mas arrastaria a biblioteca inteira para o bundle.
//
// D-853 · Fonte única. O app tinha 24 tamanhos de ícone (9 a 34 px),
// traços de 0,3 a 3 e 113 arquivos importando o lucide direto. Agora todo
// ícone passa por aqui (a catraca iconeDoTema.test cobra), e a escala é
// curta e tipada: 14 px junto de texto, 16 px em botão e barra, 20 px no
// trilho. Desenho grande (placeholder, estado vazio) usa `ilustracao`, com
// o tamanho dito em px. O traço é um só, 1,75, em todo lugar. Um nome por
// desenho: os apelidos antigos do lucide (AlertTriangle, CheckCircle2,
// Wand2) são o mesmo glifo de triangle-alert, circle-check e wand-sparkles.
// ─────────────────────────────────────────────────────────────────

const ICONS = {
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-left-to-line': ArrowLeftToLine,
  'arrow-right': ArrowRight,
  'arrow-right-to-line': ArrowRightToLine,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  ban: Ban,
  'bar-chart': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  braces: Braces,
  brain: Brain,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  camera: Camera,
  captions: Captions,
  check: Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-first': ChevronFirst,
  'chevron-last': ChevronLast,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'circle-check': CircleCheck,
  'circle-dashed': CircleDashed,
  'circle-help': CircleHelp,
  'circle-slash': CircleSlash,
  clapperboard: Clapperboard,
  clipboard: Clipboard,
  'clipboard-list': ClipboardList,
  'clipboard-paste': ClipboardPaste,
  clock: Clock,
  'clock-3': Clock3,
  command: Command,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  crop: Crop,
  download: Download,
  'edit-3': Edit3,
  eraser: Eraser,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  film: Film,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  frame: Frame,
  gauge: Gauge,
  'git-compare-arrows': GitCompareArrows,
  globe: Globe,
  'grip-vertical': GripVertical,
  hand: Hand,
  'hard-drive': HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  history: History,
  home: Home,
  image: Image,
  'image-off': ImageOff,
  'image-plus': ImagePlus,
  inbox: Inbox,
  info: Info,
  keyboard: Keyboard,
  layers: Layers,
  'layout-grid': LayoutGrid,
  'layout-template': LayoutTemplate,
  link: Link,
  'link-2': Link2,
  list: List,
  'list-checks': ListChecks,
  'list-filter': ListFilter,
  loader: Loader,
  'loader-2': Loader2,
  lock: Lock,
  maximize: Maximize,
  'maximize-2': Maximize2,
  merge: Merge,
  'message-circle': MessageCircle,
  mic: Mic,
  'minimize-2': Minimize2,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  'mouse-pointer-2': MousePointer2,
  move: Move,
  'move-horizontal': MoveHorizontal,
  package: Package,
  palette: Palette,
  'panel-bottom': PanelBottom,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  'panel-right-close': PanelRightClose,
  'panel-right-open': PanelRightOpen,
  pause: Pause,
  pen: Pen,
  pin: Pin,
  play: Play,
  plus: Plus,
  puzzle: Puzzle,
  quote: Quote,
  radio: Radio,
  'redo-2': Redo2,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  rows: Rows2,
  save: Save,
  scale: Scale,
  'scan-face': ScanFace,
  'scan-line': ScanLine,
  scissors: Scissors,
  search: Search,
  settings: Settings,
  'settings-2': Settings2,
  'shield-check': ShieldCheck,
  'skip-back': SkipBack,
  'sliders-horizontal': SlidersHorizontal,
  sparkle: Sparkle,
  sparkles: Sparkles,
  'split-square-horizontal': SplitSquareHorizontal,
  star: Star,
  sun: Sun,
  tag: Tag,
  tags: Tags,
  target: Target,
  'text-cursor-input': TextCursorInput,
  trash: Trash,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  type: Type,
  'undo-2': Undo2,
  unlock: Unlock,
  upload: Upload,
  'upload-cloud': UploadCloud,
  'user-plus': UserPlus,
  users: Users,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'wand-sparkles': WandSparkles,
  wrench: Wrench,
  x: X,
  'x-circle': XCircle,
  youtube: Youtube,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** Todos os nomes, para quem precisa percorrê-los (testes, kit). */
export const NOMES_DE_ICONE = Object.keys(ICONS) as IconName[];

// D-858 · Um conceito, um desenho. O app usava o mesmo glifo para ideias
// diferentes — a tesoura era a etapa Cortes, "Editar corte" e "Gerar
// trechos"; o avião de papel, o menu Prontos e "Subir para o TikTok"; o play,
// "Tocar vídeo" e "Informar a URL"; a lupa, "Buscar" e "Auditar". Cada
// conceito do fluxo tem agora o seu, e a catraca umConceitoUmDesenho.test
// cobra que a ação rotulada com o conceito use este glifo.
export const ICONE_DO_CONCEITO = {
  /** A IA produz algo: trechos, metadados, capa. A estrela simples da
   *  prancha — o `sparkles` (com os brilhinhos) não é este desenho. */
  iaGera: 'sparkle',
  /** Abrir para editar: o corte, a capa. O traço único da prancha — o
   *  `pencil` tem a faixa da borracha, que ela não desenha. */
  editar: 'pen',
  /** Trocar só o nome (um preset do palco). D-888: era o `pencil`, quase a
   *  caneta do Editar em 16 px — e renomear não abre nada para editar. */
  renomear: 'text-cursor-input',
  /** Mandar para fora: YouTube, TikTok, Reels. */
  publicar: 'upload',
  /** O que já pode sair. */
  prontos: 'circle-check',
  /** Ligar o corte a um vídeo já publicado fora do app. */
  urlPublicada: 'link',
  /** Ver por que a IA escolheu o que escolheu. */
  auditar: 'list-checks',
} as const satisfies Record<string, IconName>;

/** A escala inteira: 14 junto de texto, 16 em botão e barra, 20 no trilho. */
export type TamanhoDoIcone = 14 | 16 | 20;

const TRACO = 1.75;

type IconProps = {
  name: IconName;
  size?: TamanhoDoIcone;
  /** Desenho grande (placeholder, estado vazio), em px. Fora da escala de
   *  propósito: não é ícone de interface, é figura. */
  ilustracao?: number;
  /** Quando o ícone SOZINHO carrega sentido (sem texto ao lado), o que o
   *  leitor de tela diz. Sem ele, o ícone é decorativo e fica oculto. */
  rotulo?: string;
  className?: string;
  style?: React.CSSProperties;
};

export function Icon({ name, size = 14, ilustracao, rotulo, className, style }: IconProps) {
  const Glyph = ICONS[name];
  return (
    <Glyph
      size={ilustracao ?? size}
      strokeWidth={TRACO}
      className={className}
      // Ícone nunca encolhe: numa linha flex apertada (trilha longa, abas da
      // Pós) o padrão `flex-shrink: 1` o espremia a 5–10 px (D-854).
      style={{ flexShrink: 0, ...style }}
      {...(rotulo ? { role: 'img', 'aria-label': rotulo } : { 'aria-hidden': true })}
    />
  );
}
